# Generated by Django 4.2.11 on 2024-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LearningSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("section", models.IntegerField()),
                ("title", models.TextField()),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LearningQuiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("section", models.IntegerField()),
                ("number", models.IntegerField()),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("options", models.ManyToManyField(to="quiz.learningoption")),
            ],
        ),
    ]
